---
# Global variables for all hosts

# SSH Configuration


# Firewall Configuration
firewall_allowed_tcp_ports:
  - 22
  - "{{ nginx_ssl_port }}"

# PKI Configuration
pki_ca_organization: ""
pki_ca_common_name: ""
pki_server_organization: ""
pki_server_common_name: "web.local.local"

# Nginx Configuration
nginx_port: 80
nginx_ssl_port: 443
backend_server:  # IP address of the backend server
backend_port: 8080

# Suricata Configuration
suricata_interface: eth0
suricata_home_net: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
suricata_external_net: "!$HOME_NET"
suricata_run_mode: "IDS"  # IDS or IPS mode

# Auditd Configuration


# PAM Configuration
