---
# Global variables for all hosts

# SSH Configuration
firewall_ssh_ports:
  - 22

# Firewall Configuration
firewall_allowed_tcp_ports:
  - 22
  - "{{ nginx_ssl_port }}"

firewall_backend_server: "{{ backend_server }}"
firewall_backend_port: "{{ backend_port }}"

# Firewall logging and rate limiting
firewall_log_level: 4
firewall_log_rate_limit: "5/min"
firewall_ssh_rate_limit_seconds: 60
firewall_ssh_rate_limit_hitcount: 4
firewall_web_rate_limit_seconds: 10
firewall_web_rate_limit_hitcount: 20

# PKI Configuration
pki_ca_organization: ""
pki_ca_common_name: ""
pki_server_organization: ""
pki_server_common_name: "web.local.local"

# Nginx Configuration
nginx_port: 80
nginx_ssl_port: 443
backend_server:  # IP address of the backend server
backend_port: 8080

# Suricata Configuration
suricata_interface: eth0
suricata_home_net: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
suricata_external_net: "!$HOME_NET"
suricata_run_mode: "IDS"  # IDS or IPS mode

# Fail2ban Configuration
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 5
fail2ban_ssh_maxretry: 3
fail2ban_ssh_bantime: 7200
fail2ban_nginx_bantime: 3600
fail2ban_nginx_maxretry: 6

# Auditd Configuration
auditd_num_logs: 5
auditd_max_log_file: 100
auditd_max_log_file_action: rotate
auditd_space_left: 75
auditd_space_left_action: email
auditd_admin_space_left: 50
auditd_admin_space_left_action: halt
auditd_disk_full_action: suspend
auditd_disk_error_action: suspend
auditd_tcp_port: 60
auditd_logrotate_rotate: 60

# PAM Configuration

