---
# Global variables for all hosts

# SSH Configuration


# Firewall Configuration
firewall_allowed_tcp_ports:
  - 22
  - "{{ nginx_port }}"
  - "{{ nginx_ssl_port }}"

# Nginx Configuration
nginx_port: 80
nginx_ssl_port: 443
backend_server:  # IP address of the backend server
backend_port: 8080

# Suricata Configuration


# Auditd Configuration


# PAM Configuration
