---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart suricata
  systemd:
    name: suricata
    state: restarted

- name: reload suricata
  systemd:
    name: suricata
    state: reloaded

- name: stop suricata
  systemd:
    name: suricata
    state: stopped 