---
- name: restart suricata
  systemd:
    name: suricata
    state: restarted

- name: reload suricata
  systemd:
    name: suricata
    state: reloaded

- name: stop suricata
  systemd:
    name: suricata
    state: stopped 