---
- name: Bastion Host Security Hardening
  hosts: bastion
  become: yes
  gather_facts: yes

  roles:
    - ssh
    - pam
    - firewall
    - suricata
    - auditd

  post_tasks:
    - name: Ensure all services are running and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - sshd
        - suricata
        - auditd
      ignore_errors: yes