---
all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: 192.168.187.129
          ansible_user: root
          ansible_ssh_port: 22
          ansible_python_interpreter: /usr/bin/python3
          suricata_interface: ens33
          # ansible_ssh_private_key_file: ~/.ssh/id_ed25519  # Using key auth instead of password