---
- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: reload auditd
  systemd:
    name: auditd
    state: reloaded

- name: stop auditd
  systemd:
    name: auditd
    state: stopped 