---
- name: restart auditd
  shell: >
    service auditd restart || systemctl reload auditd || true
  ignore_errors: yes

- name: reload auditd
  shell: >
    augenrules --load || true &&
    kill -HUP $(pidof auditd) || true
  ignore_errors: yes

- name: stop auditd
  systemd:
    name: auditd
    state: stopped 