---
- name: Install auditd
  package:
    name: auditd
    state: present

- name: Install audit utilities
  package:
    name: "{{ item }}"
    state: present
  loop:
    - audispd-plugins
    - audit-libs
  ignore_errors: yes

- name: Create audit rules directory
  file:
    path: /etc/audit/rules.d
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Configure auditd main configuration
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    backup: yes
    mode: '0640'
    owner: root
    group: root
  notify: restart auditd

- name: Configure audit rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/bastion.rules
    mode: '0640'
    owner: root
    group: root
  notify: restart auditd

- name: Load audit rules
  command: augenrules --load
  changed_when: false
  ignore_errors: yes

- name: Start and enable auditd
  systemd:
    name: auditd
    state: started
    enabled: yes

- name: Configure logrotate for audit logs
  template:
    src: audit.logrotate.j2
    dest: /etc/logrotate.d/audit
    mode: '0644'
    owner: root
    group: root 