---
- name: Bastion Host Security Hardening
  hosts: bastion
  become: yes
  gather_facts: yes

  roles:
#    - ssh
#    - pam
    - role: firewall
      tags: firewall
    - role: pki
      tags: pki
    - role: nginx
      tags: nginx
    - role: fail2ban
      tags: fail2ban
    - role: yay
      tags: yay
    - role: suricata
      tags: suricata
    - role: auditd
      tags: auditd

  post_tasks:
    - name: Ensure all services are running and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - sshd
        - nginx
        - fail2ban
        - suricata
        - auditd
      ignore_errors: yes
      tags: always